name: Playwright e2e tests

env:
    NODE_VERSION: 18.12.0
    
on:
    push:
      branches:
        - main
        - jest-playwright

jobs:          
    tests:
      runs-on: ubuntu-latest

      steps:
        - name: copy source code
          uses: actions/checkout@v2

        - name: Setup NodeJS v${{ env.NODE_VERSION }}
          uses: actions/setup-node@v2
          with:
            node-version: ${{ env.NODE_VERSION }}

        - name: install nodejs dependencies
          run: |
              npm ci
          
        - name: run tests
          run: |
              npm run test:e2e
          env: 
            APP_URL: https://www.twitch.tv
            API_URL: https://gql.twitch.tv/gql
            BROWSER_TYPE: "chrome"
            TESTS_PATH: "**/specs/**/*.test.[jt]s?(x)"
            HEADLESS: true
            FORCE_COLOR: 1